name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pac-Man
        uses: ghaction-x/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          commit_and_push: true
          output_dir: assets
