name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: humaNaveed/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs_folder: assets

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Pac-Man contribution graph"
          branch: main
